export default {
  modelLogo: [
    require('@assets/model_tesla.png'),
    require('@assets/model_hy.png'),
    require('@assets/model_kia.png'),
    require('@assets/model_genesis.png'),
    require('@assets/model_che.png'),
    require('@assets/model_bez.png'),
    require('@assets/model_bmw.png'),
    require('@assets/model_audi.png'),
    require('@assets/model_etc.png'),
  ],
  modelName: [
    '테슬라',
    '현대',
    '기아',
    '제네시스',
    '쉐보레',
    '벤츠',
    'BMW',
    '아우디',
    '기타',
  ],
  // -기타: GM, 르노코리아자동차, 쌍용자동차, Nissan, JAGUAR,
  // CITROEN, PEUGEOT
  현대: ['코나 Electric', '아이오닉 Electric', '아이오닉 5', '포터2 Electric'],
  제네시스: ['G80 Electrified ', 'G70 Electrified', 'GV60 (EV)'],
  기아: ['니로 EV', '봉고3 EV ', '쏘울 EV', '레이 EV ', 'EV6 (EV)'],
  쉐보레: ['볼트 EV', '스파크 EV'],
  테슬라: ['Model 3', 'Model Y', 'Model X', 'Model S'],
  벤츠: ['EQC', 'EQA', 'EQS'],
  BMW: ['i3', 'i4', 'i4 M50', 'iX3', 'iX', 'i7'],
  아우디: ['e-Tron'],
};
